### ISSUE TITLE
an unsupported modell: lumi.plug.sacn03

### ISSUE THREAD

**Issue by miniknife88** [niceboygithub/AqaraGateway#5]
Aqara Socket H1 USB [QBCZ15LM]
model: lumi.plug.sacn03

USB can be controlled independently

**mqtt log**:
`{"cmd":"heartbeat","id":2000009335,"time":1614578722143,"rssi":-39,"params":[{"did":"lumi.4cf8cdf3c87c700","time":1614578722143,"zseq":207,"res_list":[{"res_name":"4.1.85","value":1},{"res_name":"8.0.2006","value":30},{"res_name":"0.12.85","value":0},{"res_name":"0.13.85","value":0.04},{"res_name":"0.11.85","value":235251},{"res_name":"8.0.2002","value":1},{"res_name":"8.0.2022","value":32},{"res_name":"8.0.2023","value":1},{"res_name":"8.0.2007","value":119}]}]}

{"cmd":"report","id":4097,"did":"lumi.4cf8cdf3c87c700","time":1614578694845,"rssi":-39,"zseq":187,"params":[{"res_name":"4.1.85","value":1}],"dev_src":"0"}

{"cmd":"report","id":4107,"did":"lumi.4cf8cdf3c87c700","time":1614578930825,"rssi":-39,"zseq":198,"params":[{"res_name":"4.2.85","value":1}],"dev_src":"0"}

`

**Comment by miniknife88** [comment]
Aqara Scene Panel [ZNCJMB14LM]
model: lumi.switch.n4acn4

The function of this device is more complicated, basically a switch with three buttons

**mqtt log**:
`{"cmd":"report","id":4136,"did":"lumi.4cf8cdf3c801f42","time":1614579691430,"rssi":-50,"zseq":230,"params":[{"res_name":"4.1.85","value":1}],"dev_src":"0"}

{"cmd":"report","id":4144,"did":"lumi.4cf8cdf3c801f42","time":1614579753172,"rssi":-51,"zseq":239,"params":[{"res_name":"4.2.85","value":1}],"dev_src":"0"}

{"cmd":"write_ack","id":4145,"did":"lumi.4cf8cdf3c801f42","dev_src":"0","time":1614579788961,"rssi":-51,"zseq":240,"params":[{"res_name":"4.3.85","value":1}]}

{"cmd":"heartbeat","id":2000009383,"time":1614579802316,"rssi":-49,"params":[{"did":"lumi.4cf8cdf3c801f42","time":1614579802316,"zseq":243,"res_list":[{"res_name":"4.1.85","value":0},{"res_name":"4.2.85","value":0},{"res_name":"4.3.85","value":1},{"res_name":"8.0.2006","value":32},{"res_name":"0.12.85","value":0},{"res_name":"0.13.85","value":0},{"res_name":"0.11.85","value":236739},{"res_name":"8.0.2002","value":1},{"res_name":"8.0.2223","value":"4.2.4_0528"},{"res_name":"8.0.2007","value":90}]}]}
`

**Comment by miniknife88** [comment]
Aqara RGBW LED Controller T1 [ZNTGMK11LM]
model: lumi.light.rgbac1

**mqtt log**:
`{"cmd":"report","id":4157,"did":"lumi.4cf8cdf3c87f3e3","time":1614580201019,"rssi":-53,"zseq":254,"params":[{"res_name":"4.1.85","value":1}],"dev_src":"0"}
{"cmd":"report","id":2000009400,"did":"lumi.4cf8cdf3c87f3e3","time":1614580204764,"rssi":-52,"zseq":148,"params":[{"res_name":"0.12.85","value":2.73}],"dev_src":"0"}
{"cmd":"report","id":2000009399,"did":"lumi.4cf8cdf3c87f3e3","time":1614580202718,"rssi":-53,"zseq":147,"params":[{"res_name":"14.1.85","value":31}],"dev_src":"0"}
{"cmd":"write","did":"lumi.4cf8cdf3c87f3e3","id":4181,"params":[{"res_name":"14.8.85","value":1357140924}]}
{"cmd":"report","id":4164,"did":"lumi.4cf8cdf3c87f3e3","time":1614580316961,"rssi":-52,"zseq":150,"params":[{"res_name":"14.2.85","value":0},{"res_name":"14.8.85","value":1332040887}],"dev_src":"0"}`

"14.8.85" RGB? need confirm

**Comment by miniknife88** [comment]
model: lumi.plug.sacn03

"4.2.85" should be of switch type, not a binary sensor

**Comment by niceboygithub** [comment]
> model: lumi.plug.sacn03
> 
> "4.2.85" should be of switch type, not a binary sensor

OK, thanks

**Comment by miniknife88** [comment]
after testing, correct:

`{
    # on/off, power measurement
    'lumi.plug.sacn03': ["Aqara", "Socket H1 USB", "QBCZ15LM"],  #  @miniknife88
    'params': [
        ['0.12.85', 'load_power', 'power', 'sensor'],
        ['0.13.85', None, 'consumption', 'sensor'],
        ['4.1.85', 'channel_0', 'switch', 'switch'], 
        ['4.2.85', 'channel_1', 'switch_usb', 'switch'],
    ]
}`

**Comment by miniknife88** [comment]
lumi.motion.agl02 Has illumination attributes
`{
    # motion sensor with illuminance
    'lumi.sensor_motion.aq2': ["Aqara", "Motion Sensor", "RTCGQ11LM"],
    'lumi.motion.agl02': ["Aqara", "Motion Sensor T1", "RTCGQ12LM"],  # miniknife88 
    'params': [
        ['0.3.85', 'lux', 'illuminance_lux', None],
        ['0.4.85', 'illumination', 'illuminance', 'sensor'],
        ['3.1.85', None, 'motion', 'binary_sensor'],
        ['8.0.2001', 'battery', 'battery', 'sensor'],
    ]
}`

**Comment by miniknife88** [comment]
lumi.motion.agl04 can't trigger, correct:

`{
    # motion sensor
    'lumi.sensor_motion': ["Xiaomi", "Motion Sensor", "RTCGQ01LM"],
    'lumi.motion.agl04': ["Aqara", "Precision Motion Sensor", "RTCGQ13LM"],
    'params': [
        ['3.1.85', None, 'motion', 'binary_sensor'],
        ['8.0.2001', 'battery', 'battery', 'sensor'],
    ]
}`

**Comment by miniknife88** [comment]
utils.py Line 192 should be deleted

**Comment by niceboygithub** [comment]
Please help test on devices.
https://github.com/niceboygithub/AqaraGateway/commit/59b2fcbb38bc4f8b167b870f0945c34d645080a5

**Comment by miniknife88** [comment]
model: lumi.light.rgbac1 - **already fixed**
model: lumi.motion.agl04 - **already fixed**
model: lumi.motion.agl02 - **already fixed**
model: lumi.weather - **no illuminance attributes, should be the pressure attribute**
model: lumi.plug.sacn03 - **missing USB control entity**

utils.py line 74 change to '['4.2.85', 'channel_1', 'switch_usb', 'switch'],' 
After testing, normal~

**Comment by miniknife88** [comment]
The latest version is tested:

model: lumi.light.rgbac1 - **already fixed**
model: lumi.motion.agl04 - **already fixed**
model: lumi.motion.agl02 - **already fixed**
model: lumi.plug.sacn03 - **already fixed**
model: lumi.weather - **pressure attributes is Unknown, will not update**

![5555](https://user-images.githubusercontent.com/30946790/109610470-c7de1380-7b67-11eb-9550-114b50e262f1.png)

**Comment by miniknife88** [comment]
model: lumi.light.rgbac1 has RGB attributes
"res_name":"20.4.85" Not defined，log:

`{"cmd":"report","id":7866,"did":"lumi.4cf8cdf3c801f42","time":1614701312640,"rssi":-51,"zseq":244,"params":[{"res_name":"20.4.85","value":"0004cf8cdf3c87f3e308"}],"dev_src":"0"}`

Corresponding to RGB value：#FFF0E8

`{"cmd":"report","id":7869,"did":"lumi.4cf8cdf3c801f42","time":1614701342467,"rssi":-50,"zseq":246,"params":[{"res_name":"20.4.85","value":"0004cf8cdf3c87f3e308"}],"dev_src":"0"}`

Corresponding to RGB value：#E7F3FE

**Comment by niceboygithub** [comment]
The value 0004cf8cdf3c87f3e308  is the same.

I add debug log in the latest commit. 
To get more info to help to debug.

**Comment by miniknife88** [comment]
Latest log：
[debug.log](https://github.com/niceboygithub/AqaraGateway/files/6073421/debug.log)

"14.8.85" is colro_temp, not rgb color

entity: lumi.4cf8cdf3c87f3e3 
model: lumi.light.rgbac1

**Comment by miniknife88** [comment]
[debug_rgb.log](https://github.com/niceboygithub/AqaraGateway/files/6086027/debug_rgb.log)
entity: lumi.4cf8cdf3c87f3e3
model: lumi.light.rgbac1

The device still does not display RGB attributes, and the attribute panel does not have a color palette

**Comment by niceboygithub** [comment]
> [debug_rgb.log](https://github.com/niceboygithub/AqaraGateway/files/6086027/debug_rgb.log)
> entity: lumi.4cf8cdf3c87f3e3
> model: lumi.light.rgbac1
> 
> The device still does not display RGB attributes, and the attribute panel does not have a color palette

Can you test line 210 in utils.py and have test?
`        ['14.8.85', 'light_level', 'rgb_color', 'light'],`

**Comment by miniknife88** [comment]
After changing 210 lines, the color palette is still not displayed

**Comment by miniknife88** [comment]
lumi.light.rgbac1 has a palette, but when I choose the color, I get an error:

`2021-03-08 23:20:36 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139941161812224] required argument is not an integer
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 141, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1488, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1523, in _execute_service
await handler.job.target(service_call)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 642, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 681, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 679, in _handle_entity_call
await result
File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 235, in async_handle_light_on_service
await light.async_turn_on(**params)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 707, in async_turn_on
await self.hass.async_add_executor_job(ft.partial(self.turn_on, **kwargs))
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/aqara_gateway/light.py", line 112, in turn_on
rgbhex = binascii.hexlify(struct.pack("BBBB", *rgba)).decode("ASCII")
struct.error: required argument is not an integer`

**Comment by miniknife88** [comment]
After the update, the error log is no longer generated for the selected color, but the color of the light has not changed in fact

**Comment by niceboygithub** [comment]
> After the update, the error log is no longer generated for the selected color, but the color of the light has not changed in fact

Looks that the values were not excepted as my code.
Can you add debug logs?
```

        if (ATTR_HS_COLOR in kwargs or ATTR_BRIGHTNESS in kwargs or
                self._attr == ATTR_RGB_COLOR):
            self.debug(f"brightness : {self._brightness}")
            self.debug(f"hs : {self._hs}")
            self.debug(f"rgb_color : {self._rgb_color}")
            self.debug(f"color_temp : {self._color_temp}")
            rgb = color_util.color_hs_to_RGB(*self._hs)
            rgba = (self._brightness,) + rgb
            if isinstance(self._brightness, int):
                rgbhex = binascii.hexlify(struct.pack("BBBB", *rgba)).decode("ASCII")
                rgbhex = int(rgbhex, 16)
                payload[ATTR_HS_COLOR] = rgbhex
        self.debug(f"payload : {payload}")
```

**Comment by miniknife88** [comment]
add debug logs(light.0x4cf8cdf3c87f3e3_light):

[debug.log](https://github.com/niceboygithub/AqaraGateway/files/6108830/debug.log)

**Comment by niceboygithub** [comment]
> add debug logs(light.0x4cf8cdf3c87f3e3_light):
> 
> [debug.log](https://github.com/niceboygithub/AqaraGateway/files/6108830/debug.log)

2021-03-09 21:31:23  DEBUG  gateway  192.168.1.111: MQTT on_message: zigbee/send {"cmd":"write_rsp","id":0,"time":1615296683291,"did":"lumi.4cf8cdf3c87f3e3","zseq":229,"results":[{"res_name":"14.8.85","value":33498203,"error_code":0}]}

The value of rgb was sent to lumi.light.rgbac1, but it may not correct value

Need see how Aqara Home set the rgb value. Please try to get the log using the following commands
`
telnet [your gateway ip]
`
After login, then
`
setprop persist.app.debug_log true
reboot
`
After gateway reboot, use Aqara Home app to adjust the rgb color of lumi.light.rgbac1.
Login again. 
`
cat /tmp/bmlog.txt
`

**Comment by miniknife88** [comment]
[bmlog.txt](https://github.com/niceboygithub/AqaraGateway/files/6112993/bmlog.txt)

**Comment by niceboygithub** [comment]
Thanks
I forgot to say.
Need to adjust color as
All Red, then see the value in  {"res_name":"14.8.85","value":?}
And all green, all blue.

**Comment by miniknife88** [comment]
Red: ( value: 2641515792)
[red_ff2721.log](https://github.com/niceboygithub/AqaraGateway/files/6113544/red_ff2721.log)


green: (value: 1405651597)
[green_81f947.log](https://github.com/niceboygithub/AqaraGateway/files/6113546/green_81f947.log)

blue: (value: 769596272)
[blue_504efe.log](https://github.com/niceboygithub/AqaraGateway/files/6113548/blue_504efe.log)

**Comment by miniknife88** [comment]
> Can you try these codes in light.py?
> 
> ```
>                 rgbhex = binascii.hexlify(struct.pack("BBBB", *rgba)).decode("ASCII")
>                 rgbhex = int(rgbhex, 16)
>                 if self.device['type'] == 'zigbee':
>                     payload[ATTR_HS_COLOR] = rgbhex * 150
>                 else:
>                     payload[ATTR_HS_COLOR] = rgbhex
> ```

After testing, there is no effect, and there is no error report
[debug.txt](https://github.com/niceboygithub/AqaraGateway/files/6114295/debug.txt)

**Comment by niceboygithub** [comment]
> > Can you try these codes in light.py?
> > ```
> >                 rgbhex = binascii.hexlify(struct.pack("BBBB", *rgba)).decode("ASCII")
> >                 rgbhex = int(rgbhex, 16)
> >                 if self.device['type'] == 'zigbee':
> >                     payload[ATTR_HS_COLOR] = rgbhex * 150
> >                 else:
> >                     payload[ATTR_HS_COLOR] = rgbhex
> > ```
> 
> After testing, there is no effect, and there is no error report
> [debug.txt](https://github.com/niceboygithub/AqaraGateway/files/6114295/debug.txt)

From this log, I did not see the 14.8.85 (rgb_color) was sent.
only power_status
`
 2021-03-10 16:08:11  DEBUG  gateway  192.168.1.111: MQTT on_message: zigbee/recv {"cmd":"write","did":"lumi.4cf8cdf3c87f3e3","params":[{"res_name":"4.1.85","value":1}]}
`

**Comment by miniknife88** [comment]
Test again and found that only the color selected for the first time is valid

[debug.txt](https://github.com/niceboygithub/AqaraGateway/files/6114631/debug.txt)

**Comment by niceboygithub** [comment]
> Test again and found that only the color selected for the first time is valid, the strange thing is that it doesn’t work every time, the second test has no effect at all
> 
> [debug.txt](https://github.com/niceboygithub/AqaraGateway/files/6114631/debug.txt)
> [debug_1.txt](https://github.com/niceboygithub/AqaraGateway/files/6114796/debug_1.txt)

maybe 150 is too big.
You can check the log with such message, "results":[{"res_name":"14.8.85","value":1258454113,"error_code":0}]}"
The error_code must be 0.
But the way, is the color corrected?

**Comment by miniknife88** [comment]
Latest version error：

`2021-03-10 20:52:13 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 282, in async_update_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 321, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 485, in state_attributes
data[ATTR_HS_COLOR] = (round(hs_color[0], 3), round(hs_color[1], 3))
TypeError: 'float' object is not subscriptable
2021-03-10 20:52:13 ERROR (Thread-6) [root] Uncaught thread exception
Traceback (most recent call last):
File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3452, in _thread_main
self.loop_forever(retry_first_connection=True)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1779, in loop_forever
rc = self.loop(timeout, max_packets)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1181, in loop
rc = self.loop_read(max_packets)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1572, in loop_read
rc = self._packet_read()
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2310, in _packet_read
rc = self._packet_handle()
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2936, in _packet_handle
return self._handle_publish()
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3216, in _handle_publish
self._handle_on_message(message)
File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3444, in _handle_on_message
self.on_message(self, self._userdata, message)
File "/config/custom_components/aqara_gateway/core/gateway.py", line 400, in on_message
self._process_message(payload)
File "/config/custom_components/aqara_gateway/core/gateway.py", line 580, in _process_message
handler(payload)
File "/config/custom_components/aqara_gateway/light.py", line 92, in update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 295, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 321, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 485, in state_attributes
data[ATTR_HS_COLOR] = (round(hs_color[0], 3), round(hs_color[1], 3))
TypeError: 'float' object is not subscriptable
2021-03-10 20:52:19 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 282, in async_update_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 321, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 485, in state_attributes
data[ATTR_HS_COLOR] = (round(hs_color[0], 3), round(hs_color[1], 3))
TypeError: 'float' object is not subscriptable`

**Comment by niceboygithub** [comment]
> A new problem was found, the M1S gateway light cannot be controlled（Upgraded the latest firmware）

I have no problem controlling the gateway light of M1S no matter the original or customized 3.1.2_0013.0519 firmwares.

> Latest version error：
fixed

**Comment by miniknife88** [comment]
understood，lumi.light.rgbac1 no more error, but rgb adjustment is still invalid

**Comment by niceboygithub** [comment]
> understood，lumi.light.rgbac1 no more error, but rgb adjustment is still invalid

With multiply by 150, still can not adjust rgb?

**Comment by miniknife88** [comment]
Yes, still can't.
The other one is：lumi.plug.sacn03 and lumi.remote.rkba01 status will become unavailable.

**Comment by niceboygithub** [comment]
> Yes, still can't.
> The other one is：lumi.plug.sacn03 and lumi.remote.rkba01 status will become unavailable.

Can you provide the logs and screenshots?
Maybe there are some mqtt messages which were not handled well.

**Comment by miniknife88** [comment]
lumi.54ef44100003828e 

lumi.remote.rkba01 will be unavailable soon, lumi.plug.sacn03 take longer...

[debug_11.txt](https://github.com/niceboygithub/AqaraGateway/files/6121048/debug_11.txt)

![h1](https://user-images.githubusercontent.com/30946790/110750233-23518500-827d-11eb-9c7b-141ee533e91f.png)
![h1_1](https://user-images.githubusercontent.com/30946790/110750250-28aecf80-827d-11eb-99d9-6093e1da998e.png)

**Comment by niceboygithub** [comment]
> 54ef44100003828e

The lqi of lumi.plug.sacn03 is around 46.
The lqi of lumi.plug.sacn03 is around 35.
That's mean that the quality of zigbee signal is very bad. You need change the place of gateway. Or add router type devices.

**Comment by miniknife88** [comment]
There are router-type devices near this device, and in the Aqara home app, these devices have always been normal

**Comment by niceboygithub** [comment]
![image](https://user-images.githubusercontent.com/74046071/110755788-4d5a7580-8284-11eb-8202-3aebc48a8444.png)

From this picture, you can see that the lumi.remote.rkba01 was report offline/online several times.
Maybe it is this kind of device. Then need to ignore the offline report of it.
Try to comment line 575, 576 of gateway.py

Remember, zigbee to mqtt is more real time than Aqara Home app.

**Comment by miniknife88** [comment]
after comment line 575, 576, everything is good!
